apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: rnd-fn
data:
  fieldprefix: selenium-hub
  fieldSpecs:
  - path: metadata/name
  - path: metadata/labels/app
  - path: spec/selector/app
    kind: Service
